# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5610ab00a9b697993df281baa5a16b1ce4d9005591dcd45dc54537fe38e76098998079ce07b89d8c9e36399cc1a11f61cb5a3db0ed6b2d55f370c228b3b78d2

test:
  secret_key_base: 821706b2d9f5a5c7541a6f429054b4fa63267865c8c94448acf5b93921ef0b75bb94c12508fa3390be317c369100fc112acfd00b65f3972f1b778a495f0edd03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
